<?php

/**
 * Payment API
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Model;

/**
 * CardBrandType Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

class CardBrandType
{
    public const VISA = 'VISA';
    public const MASTERCARD = 'MASTERCARD';
    public const AMEX = 'AMEX';
    public const HIPERCARD = 'HIPERCARD';
    public const ELO = 'ELO';
}
