<?php

/**
 * Payment API
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Request\pay;

use \ArrayAccess;
use Request\AlipayRequest;

/**
 * AlipayPayConsultRequest Class Doc Comment
 *
 * @category Class
 * @package  request
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AlipayPayConsultRequest   extends AlipayRequest  implements ModelInterface, ArrayAccess
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AlipayPayConsultRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'productCode' => '\request\model\ProductCodeType',
        'paymentAmount' => '\request\model\Amount',
        'userRegion' => 'string',
        'merchantRegion' => 'string',
        'settlementStrategy' => '\request\model\SettlementStrategy',
        'allowedPaymentMethodRegions' => 'string[]',
        'env' => '\request\model\Env',
        'buyer' => '\request\model\Buyer',
        'merchantAccountId' => 'string',
        'paymentFactor' => '\request\model\PaymentFactor',
        'allowedPaymentMethods' => 'string[]',
        'blockedPaymentMethods' => 'string[]',
        'region' => 'string',
        'customerId' => 'string',
        'referenceUserId' => 'string',
        'extendInfo' => 'string',
        'merchant' => '\request\model\Merchant',
        'allowedPspRegions' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'productCode' => null,
        'paymentAmount' => null,
        'userRegion' => null,
        'merchantRegion' => null,
        'settlementStrategy' => null,
        'allowedPaymentMethodRegions' => null,
        'env' => null,
        'buyer' => null,
        'merchantAccountId' => null,
        'paymentFactor' => null,
        'allowedPaymentMethods' => null,
        'blockedPaymentMethods' => null,
        'region' => null,
        'customerId' => null,
        'referenceUserId' => null,
        'extendInfo' => null,
        'merchant' => null,
        'allowedPspRegions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'productCode' => false,
        'paymentAmount' => false,
        'userRegion' => false,
        'merchantRegion' => false,
        'settlementStrategy' => false,
        'allowedPaymentMethodRegions' => false,
        'env' => false,
        'buyer' => false,
        'merchantAccountId' => false,
        'paymentFactor' => false,
        'allowedPaymentMethods' => false,
        'blockedPaymentMethods' => false,
        'region' => false,
        'customerId' => false,
        'referenceUserId' => false,
        'extendInfo' => false,
        'merchant' => false,
        'allowedPspRegions' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'productCode' => 'productCode',
        'paymentAmount' => 'paymentAmount',
        'userRegion' => 'userRegion',
        'merchantRegion' => 'merchantRegion',
        'settlementStrategy' => 'settlementStrategy',
        'allowedPaymentMethodRegions' => 'allowedPaymentMethodRegions',
        'env' => 'env',
        'buyer' => 'buyer',
        'merchantAccountId' => 'merchantAccountId',
        'paymentFactor' => 'paymentFactor',
        'allowedPaymentMethods' => 'allowedPaymentMethods',
        'blockedPaymentMethods' => 'blockedPaymentMethods',
        'region' => 'region',
        'customerId' => 'customerId',
        'referenceUserId' => 'referenceUserId',
        'extendInfo' => 'extendInfo',
        'merchant' => 'merchant',
        'allowedPspRegions' => 'allowedPspRegions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'productCode' => 'setProductCode',
        'paymentAmount' => 'setPaymentAmount',
        'userRegion' => 'setUserRegion',
        'merchantRegion' => 'setMerchantRegion',
        'settlementStrategy' => 'setSettlementStrategy',
        'allowedPaymentMethodRegions' => 'setAllowedPaymentMethodRegions',
        'env' => 'setEnv',
        'buyer' => 'setBuyer',
        'merchantAccountId' => 'setMerchantAccountId',
        'paymentFactor' => 'setPaymentFactor',
        'allowedPaymentMethods' => 'setAllowedPaymentMethods',
        'blockedPaymentMethods' => 'setBlockedPaymentMethods',
        'region' => 'setRegion',
        'customerId' => 'setCustomerId',
        'referenceUserId' => 'setReferenceUserId',
        'extendInfo' => 'setExtendInfo',
        'merchant' => 'setMerchant',
        'allowedPspRegions' => 'setAllowedPspRegions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'productCode' => 'getProductCode',
        'paymentAmount' => 'getPaymentAmount',
        'userRegion' => 'getUserRegion',
        'merchantRegion' => 'getMerchantRegion',
        'settlementStrategy' => 'getSettlementStrategy',
        'allowedPaymentMethodRegions' => 'getAllowedPaymentMethodRegions',
        'env' => 'getEnv',
        'buyer' => 'getBuyer',
        'merchantAccountId' => 'getMerchantAccountId',
        'paymentFactor' => 'getPaymentFactor',
        'allowedPaymentMethods' => 'getAllowedPaymentMethods',
        'blockedPaymentMethods' => 'getBlockedPaymentMethods',
        'region' => 'getRegion',
        'customerId' => 'getCustomerId',
        'referenceUserId' => 'getReferenceUserId',
        'extendInfo' => 'getExtendInfo',
        'merchant' => 'getMerchant',
        'allowedPspRegions' => 'getAllowedPspRegions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('productCode', $data ?? [], null);
        $this->setIfExists('paymentAmount', $data ?? [], null);
        $this->setIfExists('userRegion', $data ?? [], null);
        $this->setIfExists('merchantRegion', $data ?? [], null);
        $this->setIfExists('settlementStrategy', $data ?? [], null);
        $this->setIfExists('allowedPaymentMethodRegions', $data ?? [], null);
        $this->setIfExists('env', $data ?? [], null);
        $this->setIfExists('buyer', $data ?? [], null);
        $this->setIfExists('merchantAccountId', $data ?? [], null);
        $this->setIfExists('paymentFactor', $data ?? [], null);
        $this->setIfExists('allowedPaymentMethods', $data ?? [], null);
        $this->setIfExists('blockedPaymentMethods', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], null);
        $this->setIfExists('customerId', $data ?? [], null);
        $this->setIfExists('referenceUserId', $data ?? [], null);
        $this->setIfExists('extendInfo', $data ?? [], null);
        $this->setIfExists('merchant', $data ?? [], null);
        $this->setIfExists('allowedPspRegions', $data ?? [], null);

         $this->setPath("/ams/api/v1/payments/consult"); 
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['productCode'] === null) {
            $invalidProperties[] = "'productCode' can't be null";
        }
        if ($this->container['paymentAmount'] === null) {
            $invalidProperties[] = "'paymentAmount' can't be null";
        }
        if ($this->container['env'] === null) {
            $invalidProperties[] = "'env' can't be null";
        }
        if ($this->container['allowedPaymentMethods'] === null) {
            $invalidProperties[] = "'allowedPaymentMethods' can't be null";
        }
        if ($this->container['blockedPaymentMethods'] === null) {
            $invalidProperties[] = "'blockedPaymentMethods' can't be null";
        }
        if ($this->container['region'] === null) {
            $invalidProperties[] = "'region' can't be null";
        }
        if ($this->container['customerId'] === null) {
            $invalidProperties[] = "'customerId' can't be null";
        }
        if ($this->container['referenceUserId'] === null) {
            $invalidProperties[] = "'referenceUserId' can't be null";
        }
        if ($this->container['extendInfo'] === null) {
            $invalidProperties[] = "'extendInfo' can't be null";
        }
        if ($this->container['merchant'] === null) {
            $invalidProperties[] = "'merchant' can't be null";
        }
        if ($this->container['allowedPspRegions'] === null) {
            $invalidProperties[] = "'allowedPspRegions' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets productCode
     *
     * @return \request\model\ProductCodeType
     */
    public function getProductCode()
    {
        return $this->container['productCode'];
    }

    /**
     * Sets productCode
     *
     * @param \request\model\ProductCodeType $productCode productCode
     *
     * @return self
     */
    public function setProductCode($productCode)
    {
        $this->container['productCode'] = $productCode;

        return $this;
    }

    /**
     * Gets paymentAmount
     *
     * @return \request\model\Amount
     */
    public function getPaymentAmount()
    {
        return $this->container['paymentAmount'];
    }

    /**
     * Sets paymentAmount
     *
     * @param \request\model\Amount $paymentAmount paymentAmount
     *
     * @return self
     */
    public function setPaymentAmount($paymentAmount)
    {
        $this->container['paymentAmount'] = $paymentAmount;

        return $this;
    }

    /**
     * Gets userRegion
     *
     * @return string|null
     */
    public function getUserRegion()
    {
        return $this->container['userRegion'];
    }

    /**
     * Sets userRegion
     *
     * @param string|null $userRegion The 2-letter country or region code. For more information, see ISO 3166 Country Codes standard. The payment methods will be sorted based on payment method relevance for the given user's region.
     *
     * @return self
     */
    public function setUserRegion($userRegion)
    {
        $this->container['userRegion'] = $userRegion;

        return $this;
    }

    /**
     * Gets merchantRegion
     *
     * @return string|null
     */
    public function getMerchantRegion()
    {
        return $this->container['merchantRegion'];
    }

    /**
     * Sets merchantRegion
     *
     * @param string|null $merchantRegion The country or region where the merchant operates the business. The parameter is a 2-letter country or region code that follows ISO 3166 Country Codes standard.
     *
     * @return self
     */
    public function setMerchantRegion($merchantRegion)
    {
        $this->container['merchantRegion'] = $merchantRegion;

        return $this;
    }

    /**
     * Gets settlementStrategy
     *
     * @return \request\model\SettlementStrategy|null
     */
    public function getSettlementStrategy()
    {
        return $this->container['settlementStrategy'];
    }

    /**
     * Sets settlementStrategy
     *
     * @param \request\model\SettlementStrategy|null $settlementStrategy settlementStrategy
     *
     * @return self
     */
    public function setSettlementStrategy($settlementStrategy)
    {
        $this->container['settlementStrategy'] = $settlementStrategy;

        return $this;
    }

    /**
     * Gets allowedPaymentMethodRegions
     *
     * @return string[]|null
     */
    public function getAllowedPaymentMethodRegions()
    {
        return $this->container['allowedPaymentMethodRegions'];
    }

    /**
     * Sets allowedPaymentMethodRegions
     *
     * @param string[]|null $allowedPaymentMethodRegions A list of region codes that represent the countries or regions of payment methods. The value of this parameter is a 2-letter ISO country code or GLOBAL.   Specify this parameter if you want available payment methods from specific regions to be returned. For example, if you pass in GLOBAL, global cards Visa and Mastercard are returned.
     *
     * @return self
     */
    public function setAllowedPaymentMethodRegions($allowedPaymentMethodRegions)
    {
        $this->container['allowedPaymentMethodRegions'] = $allowedPaymentMethodRegions;

        return $this;
    }

    /**
     * Gets env
     *
     * @return \request\model\Env
     */
    public function getEnv()
    {
        return $this->container['env'];
    }

    /**
     * Sets env
     *
     * @param \request\model\Env $env env
     *
     * @return self
     */
    public function setEnv($env)
    {
        $this->container['env'] = $env;

        return $this;
    }

    /**
     * Gets buyer
     *
     * @return \request\model\Buyer|null
     */
    public function getBuyer()
    {
        return $this->container['buyer'];
    }

    /**
     * Sets buyer
     *
     * @param \request\model\Buyer|null $buyer buyer
     *
     * @return self
     */
    public function setBuyer($buyer)
    {
        $this->container['buyer'] = $buyer;

        return $this;
    }

    /**
     * Gets merchantAccountId
     *
     * @return string|null
     */
    public function getMerchantAccountId()
    {
        return $this->container['merchantAccountId'];
    }

    /**
     * Sets merchantAccountId
     *
     * @param string|null $merchantAccountId The unique ID to identify a merchant account.  Specify this parameter when you use a single client ID across multiple locations.  More information about this field
     *
     * @return self
     */
    public function setMerchantAccountId($merchantAccountId)
    {
        $this->container['merchantAccountId'] = $merchantAccountId;

        return $this;
    }

    /**
     * Gets paymentFactor
     *
     * @return \request\model\PaymentFactor|null
     */
    public function getPaymentFactor()
    {
        return $this->container['paymentFactor'];
    }

    /**
     * Sets paymentFactor
     *
     * @param \request\model\PaymentFactor|null $paymentFactor paymentFactor
     *
     * @return self
     */
    public function setPaymentFactor($paymentFactor)
    {
        $this->container['paymentFactor'] = $paymentFactor;

        return $this;
    }

    /**
     * Gets allowedPaymentMethods
     *
     * @return string[]
     */
    public function getAllowedPaymentMethods()
    {
        return $this->container['allowedPaymentMethods'];
    }

    /**
     * Sets allowedPaymentMethods
     *
     * @param string[] $allowedPaymentMethods allowedPaymentMethods
     *
     * @return self
     */
    public function setAllowedPaymentMethods($allowedPaymentMethods)
    {
        $this->container['allowedPaymentMethods'] = $allowedPaymentMethods;

        return $this;
    }

    /**
     * Gets blockedPaymentMethods
     *
     * @return string[]
     */
    public function getBlockedPaymentMethods()
    {
        return $this->container['blockedPaymentMethods'];
    }

    /**
     * Sets blockedPaymentMethods
     *
     * @param string[] $blockedPaymentMethods blockedPaymentMethods
     *
     * @return self
     */
    public function setBlockedPaymentMethods($blockedPaymentMethods)
    {
        $this->container['blockedPaymentMethods'] = $blockedPaymentMethods;

        return $this;
    }

    /**
     * Gets region
     *
     * @return string
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string $region region
     *
     * @return self
     */
    public function setRegion($region)
    {
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets customerId
     *
     * @return string
     */
    public function getCustomerId()
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param string $customerId customerId
     *
     * @return self
     */
    public function setCustomerId($customerId)
    {
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets referenceUserId
     *
     * @return string
     */
    public function getReferenceUserId()
    {
        return $this->container['referenceUserId'];
    }

    /**
     * Sets referenceUserId
     *
     * @param string $referenceUserId referenceUserId
     *
     * @return self
     */
    public function setReferenceUserId($referenceUserId)
    {
        $this->container['referenceUserId'] = $referenceUserId;

        return $this;
    }

    /**
     * Gets extendInfo
     *
     * @return string
     */
    public function getExtendInfo()
    {
        return $this->container['extendInfo'];
    }

    /**
     * Sets extendInfo
     *
     * @param string $extendInfo extendInfo
     *
     * @return self
     */
    public function setExtendInfo($extendInfo)
    {
        $this->container['extendInfo'] = $extendInfo;

        return $this;
    }

    /**
     * Gets merchant
     *
     * @return \request\model\Merchant
     */
    public function getMerchant()
    {
        return $this->container['merchant'];
    }

    /**
     * Sets merchant
     *
     * @param \request\model\Merchant $merchant merchant
     *
     * @return self
     */
    public function setMerchant($merchant)
    {
        $this->container['merchant'] = $merchant;

        return $this;
    }

    /**
     * Gets allowedPspRegions
     *
     * @return string[]
     */
    public function getAllowedPspRegions()
    {
        return $this->container['allowedPspRegions'];
    }

    /**
     * Sets allowedPspRegions
     *
     * @param string[] $allowedPspRegions allowedPspRegions
     *
     * @return self
     */
    public function setAllowedPspRegions($allowedPspRegions)
    {
        $this->container['allowedPspRegions'] = $allowedPspRegions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTime) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
